[build]
  publish = "public/"
  command = "npm run build"

[build.environment]
  GATSBY_SENTRY_DSN = "https://460743dd953abc50577353529dfae924@o4508081507074048.ingest.us.sentry.io/4506513350262784"
  GATSBY_CORE_URL = "https://api.intuvist.com"
  GATSBY_WEBAPP_URL = "https://app.intuvist.com"
  GATSBY_STRIPE_PUBLIC_KEY = "pk_live_51Q7d1o08pYnCnuS2zkJlnojZWLSpynxm9ElrBULd91dABcP2DZUTcdcO35pQEsJuZDiz9dLc5PURj5kkJS3YNdFi00b6eeD9gs"
  GATSBY_FB_PIXEL_ID = "812726984135413"
  GATSBY_GOOGLE_ADS_TAG = "AW-16732869501"
  GATSBY_GOOGLE_ANALYTICS_TAG = "G-QSW70Z2GFE"
  GATSBY_POSTHOG_KEY = "phc_zq8o1MJETg7eWOWcLI224iei1EhnhIbX0AM0EVLerdt"
  GATSBY_POSTHOG_HOST = "https://us.i.posthog.com"
