name: Build and deploy
run-name: ${{ github.actor }} - Build and deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - run: npm install
      - run: npm run build
        env:
          GATSBY_OPENAI_API_KEY: ${{ secrets.GATSBY_OPENAI_API_KEY }}
          GATSBY_SENTRY_DSN: ${{ secrets.GATSBY_SENTRY_DSN }}
          GATSBY_CORE_URL: https://api.theastropal.com
          GATSBY_WEBAPP_URL: https://app.theastropal.com
          GATSBY_STRIPE_PUBLIC_KEY: pk_live_51PYUIdCWlM2pSlwevAgMytrIlAbSyIsue1Il0nKslO94qEaMcaAn542p0aMBT2ch3aYUjEaOYAJBYawJo6t4jwga00mY7TUEka
          GATSBY_FB_PIXEL_ID: "488679697025748"
          GATSBY_GOOGLE_ADS_TAG: AW-16635011402

      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: "./public"
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: v7
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: d3f3df6b-0aa9-4e23-ac64-fcb1600fa04e
